stages:
  - build  

Build NodeJS App:
   rules:
       - if: $CI_COMMIT_BRANCH == "main"
   stage: build
   script:
     - git checkout main
     - git pull origin main
     - pip3 freeze > requirements.txt
     - pip3 install -r requirements.txt
