# Generated by Django 4.1.7 on 2023-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("name", models.CharField(default="service name", max_length=500)),
                ("serial_number", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("name", models.CharField(default="service name", max_length=500)),
                ("serial_number", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Stuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=500)),
                (
                    "designation",
                    models.CharField(default="designation", max_length=500),
                ),
                ("profile_photo", models.ImageField(upload_to="media/profile-photos")),
                ("facebook", models.URLField(blank=True, max_length=1000)),
                ("twitter", models.URLField(blank=True, max_length=1000)),
                ("instagram", models.URLField(blank=True, max_length=1000)),
                ("linked_in", models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
