# Generated by Django 4.1.7 on 2023-03-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0002_qna"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="photo",
            field=models.ImageField(
                default="static/md.jpeg", upload_to="media/services"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="photo",
            field=models.ImageField(
                default="static/md.jpeg", upload_to="media/services"
            ),
        ),
    ]
