# Generated by Django 4.1.7 on 2023-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0007_alter_stuff_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="photo",
            field=models.ImageField(default="img.png", upload_to="media/services"),
        ),
        migrations.AlterField(
            model_name="service",
            name="photo",
            field=models.ImageField(default="img.png", upload_to="media/services"),
        ),
    ]
