# Generated by Django 4.1.7 on 2023-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0008_alter_application_photo_alter_service_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuff",
            name="serial_number",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
