# Generated by Django 4.1.7 on 2023-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0009_stuff_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="serial_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
