# Generated by Django 4.1.7 on 2023-03-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0012_remove_application_id_application_serial_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="serial_number",),
        migrations.RemoveField(model_name="service", name="serial_number",),
        migrations.AddField(
            model_name="application",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
