# Generated by Django 4.1.7 on 2023-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0013_remove_application_serial_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuff",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="stuff",
            name="phone",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
