# Generated by Django 4.1.7 on 2023-03-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(unique=True)),
                ("name", models.CharField(default="Category Name", max_length=100)),
                (
                    "description",
                    models.CharField(default="category description", max_length=100),
                ),
                ("question_1", models.CharField(default="---", max_length=100)),
                ("answer_1", models.CharField(default="---", max_length=100)),
                ("question_2", models.CharField(default="---", max_length=100)),
                ("answer_2", models.CharField(default="---", max_length=100)),
                ("question_3", models.CharField(default="---", max_length=100)),
                ("answer_3", models.CharField(default="---", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductHowToUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField(unique=True)),
                ("photo", models.ImageField(upload_to="media/product-how-to-use")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(unique=True)),
                ("photo", models.ImageField(upload_to="media/product-certifications")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(unique=True)),
                ("name", models.CharField(default="Product Name", max_length=100)),
                ("pack_size", models.CharField(default="Product Name", max_length=100)),
                ("use_case", models.CharField(default="Product Name", max_length=100)),
                ("visibility", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
        ),
    ]
