# Generated by Django 4.1.7 on 2023-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="answer_1",
            field=models.CharField(default="---", max_length=1000),
        ),
        migrations.AlterField(
            model_name="category",
            name="answer_2",
            field=models.CharField(default="---", max_length=1000),
        ),
        migrations.AlterField(
            model_name="category",
            name="answer_3",
            field=models.CharField(default="---", max_length=1000),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="Category Name", max_length=1000),
        ),
        migrations.AlterField(
            model_name="category",
            name="question_1",
            field=models.CharField(default="---", max_length=1000),
        ),
        migrations.AlterField(
            model_name="category",
            name="question_2",
            field=models.CharField(default="---", max_length=1000),
        ),
        migrations.AlterField(
            model_name="category",
            name="question_3",
            field=models.CharField(default="---", max_length=1000),
        ),
    ]
