# Generated by Django 4.1.7 on 2023-03-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_answer_1_alter_category_answer_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(default="category description", max_length=1000),
        ),
    ]
