# Generated by Django 4.1.7 on 2023-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photo",
            field=models.ImageField(default=None, upload_to="media/category-picture"),
        ),
    ]
