# Generated by Django 4.1.7 on 2023-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_category_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_at_homepage",
            field=models.BooleanField(default=True),
        ),
    ]
