# Generated by Django 4.1.7 on 2023-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_show_at_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dose",
            field=models.CharField(default="dose", max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="Product Name", max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="pack_size",
            field=models.CharField(default="pack size", max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="use_case",
            field=models.CharField(default="use case", max_length=1000),
        ),
    ]
