# Generated by Django 4.1.7 on 2023-03-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_dose_alter_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(unique=True)),
                ("photo", models.ImageField(upload_to="media/product-certifications")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryHowToUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField(unique=True)),
                ("photo", models.ImageField(upload_to="media/product-how-to-use")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="producthowtouse", name="product",),
        migrations.DeleteModel(name="ProductCertification",),
        migrations.DeleteModel(name="ProductHowToUse",),
    ]
