# Generated by Django 4.1.7 on 2023-03-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_categoryfeatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryfeatures",
            name="caption",
            field=models.CharField(default="caption", max_length=1000),
        ),
    ]
