# Generated by Django 4.1.7 on 2023-03-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_rename_categoryfeatures_categoryfeature"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoryFeature", new_name="CategoryFeatures",
        ),
    ]
