# Generated by Django 4.1.7 on 2023-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_rename_categoryfeature_categoryfeatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/product"),
        ),
        migrations.AlterField(
            model_name="categorycertification",
            name="photo",
            field=models.ImageField(upload_to="media/category-certifications"),
        ),
        migrations.AlterField(
            model_name="categoryfeatures",
            name="photo",
            field=models.ImageField(upload_to="media/category-features"),
        ),
    ]
